/* Header for module ISWITCH2, generated by p2c */
#ifndef ISWITCH2_H
#define ISWITCH2_H


#ifndef LOGDEF_H
#include "logdef.h"
#endif

#ifndef NSOLVER_H
#include "nsolver.h"
#endif

#ifndef GLOBALS_H
#include "globals.h"
#endif

#ifndef MYLIB_H
#include <p2c/mylib.h>
#endif

#ifndef NEWASM_H
#include <p2c/newasm.h>
#endif

#ifndef SYSGLOBALS_H
#include <p2c/sysglobals.h>
#endif

#ifndef NEWCI_H
#include <p2c/newci.h>
#endif


#ifdef ISWITCH2_G
# define vextern
#else
# define vextern extern
#endif


/*$If Float$
$float_hdw on$
$End$*/
/*$If Debugflag$
$Debug$
$End$*/



extern Void Log_iswitch2_initlib_32 PP((Analog_32_action *act));


#undef vextern

#endif /*ISWITCH2_H*/

/* End. */
