/* Header for module TC, generated by p2c */
#ifndef TC_H
#define TC_H


#ifndef LOGDEF_H
#include "logdef.h"
#endif

#ifndef NSOLVER_H
#include "nsolver.h"
#endif

#ifndef GLOBALS_H
#include "globals.h"
#endif

#ifndef MYLIB_H
#include <p2c/mylib.h>
#endif

#ifndef NEWASM_H
#include <p2c/newasm.h>
#endif

#ifndef SYSGLOBALS_H
#include <p2c/sysglobals.h>
#endif

#ifndef NEWCI_H
#include <p2c/newci.h>
#endif


#ifdef TC_G
# define vextern
#else
# define vextern extern
#endif


/*$If Float$
  $float_hdw on$
  $End$*/
/*$If Debugflag$
  $Debug$
  $End$*/


extern Void Log_opamp_initlib_32 PP((Analog_32_action *act));
extern Void Log_wramp_initlib_32 PP((Analog_32_action *act));
extern Void Log_hwr_initlib_32 PP((Analog_32_action *act));

extern Void Log_fwr_initlib_32 PP((Analog_32_action *act));


#undef vextern

#endif /*TC_H*/

/* End. */
